# Generated by Django 3.0.5 on 2020-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carDataDetails',
            fields=[
                ('carno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tariff_plan', models.CharField(default='Hourly', max_length=100)),
                ('inTime', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('outTime', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLevel',
            fields=[
                ('level_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_spots', models.CharField(max_length=50)),
                ('free_spots', models.TextField(null=True)),
                ('occupied_spots', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('plan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cost', models.CharField(default=10, max_length=100)),
                ('freetime', models.CharField(default=15, max_length=100)),
            ],
        ),
    ]
